[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cygd-validator"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = []

[project.scripts]
cygd-validate = "cygd_validator.cli:main"
